### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by meifiant** [LuPoYi/ftx-keep-lending#2]
I am newbie and would like to use your code, I clone the code to my ubunter server 20.04 and config the parameter as follow:

root@server:~/ftxlending/ftx-keep-lending# cat config.json
{
  "FTX_API_KEY": "API",
  "FTX_API_SECRET": "API",
  "CRON_JOB_AT_MINUTE": 30,
  "accounts": [
//    {
//      "subAccount": "",
//      "lendingCoins": [{ "coin": "ETH", "keepBalance": 0, "minimunHourlyRate": 0.000001 }]
//    },
    {
      "subAccount": "LENDING",
      "lendingCoins": [
        { "coin": "ETH", "keepBalance": 0, "minimunHourlyRate": 0.000001 },
//        { "coin": "XRP", "keepBalance": 0, "minimunHourlyRate": 0.000001 }
      ]
    }
  ]
}

I run the code and the following error prompt:

root@server:~/ftxlending/ftx-keep-lending# node main.js
/root/ftxlending/ftx-keep-lending/main.js:26
      const { free, total } = getBalancesResult?.result?.find((item) => item.coin === coin) || {}
                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
root@server:~/ftxlending/ftx-keep-lending#

Would you please help? Thanks.

**Comment by LuPoYi** [comment]
Thanks for the feedback. I think that is because I use some ES6 syntax.


You need to upgrade your nodejs version to 14.x
```zsh
 sudo apt update
 curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
 sudo apt-get install -y nodejs
 node -v 
// v14.15.4
```

**Comment by meifiant** [comment]
I updated nodejs to v14.15.5:

```
root@# node -v
v14.15.5
```

And still got error:

```
root@# node main.js
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: server/ftxlending/ftx-keep-lending/config.json: Unexpected token / in JSON at position 171
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/ftxlending/ftx-keep-lending/main.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

I put my FTX API key in the config.json:

```
 "FTX_API_KEY": "YOUR_FTX_API_KEY",
 "FTX_API_SECRET": "YOUR_FTX_API_SECRET",

```
however I look at your description again, it  instructed to change ".env by using your own api key, secret and set which coin you want to keep leading".

```
root@:~/ftxlending/ftx-keep-lending# ll
total 56
drwxr-xr-x 4 root root 4096 Feb 10 16:45 ./
drwxr-xr-x 4 root root 4096 Feb  9 20:56 ../
-rwxr-xr-x 1 root root  616 Feb 10 16:45 config.json*
-rwxr-xr-x 1 root root  489 Feb  9 20:55 config.json.backup*
-rwxr-xr-x 1 root root   65 Feb  9 20:55 docker-compose.yml*
-rwxr-xr-x 1 root root   92 Feb  9 20:55 Dockerfile*
drwxr-xr-x 8 root root 4096 Feb  9 20:55 .git/
-rw-r--r-- 1 root root   53 Feb  9 20:55 .gitignore
-rwxr-xr-x 1 root root 2021 Feb  9 20:55 main.js*
drwxr-xr-x 8 root root 4096 Feb  9 20:56 node_modules/
-rwxr-xr-x 1 root root  323 Feb  9 20:55 package.json*
-rw-r--r-- 1 root root  138 Feb  9 20:55 .prettierrc
-rwxr-xr-x 1 root root 1142 Feb  9 20:55 README.md*
-rwxr-xr-x 1 root root 1721 Feb  9 20:55 yarn.lock*

```
Do I doing right (change in config.json), if not.  Where is the .env file?

Thanks.

**Comment by LuPoYi** [comment]
Just use `config.json`, ignore `.env`

```
SyntaxError: server/ftxlending/ftx-keep-lending/config.json: Unexpected token / in JSON at position 171
```
It seems your `config.json` is not correct json format, do you have any '/' in this file? You need to remove the comment in this file.

**Comment by meifiant** [comment]
OK, I did use my API key in config.json.

Right, yes, I had comment out some command by using "//".  I had remove those comment, and the current cnofig.json:

```
root@# cat config.json
{
  "FTX_API_KEY": "My API key",
  "FTX_API_SECRET": "Mt secert key",
  "CRON_JOB_AT_MINUTE": 30,
  "accounts": [
      "subAccount": "LENDING",
      "lendingCoins": [
        { "coin": "USDT", "keepBalance": 0, "minimunHourlyRate": 0.000001 },
        { "coin": "XRP", "keepBalance": 0, "minimunHourlyRate": 0.000001 }
        { "coin": "BTC", "keepBalance": 0, "minimunHourlyRate": 0.000001 }
      ]
  ]
}
```

However still got error:

```
root@# node main.js
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: /root/ftxlending/ftx-keep-lending/config.json: Unexpected token : in JSON at position 189
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/ftxlending/ftx-keep-lending/main.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.
```

Sorry bother again.

**Comment by LuPoYi** [comment]
```
{ "coin": "XRP", "keepBalance": 0, "minimunHourlyRate": 0.000001 },
```
you miss a comma in the end of this line

**Comment by meifiant** [comment]
yes right, its ok now, but it prompt a kind of alert like this:

```
root@# node main.js
CronJob Before Set -> 30 * * * *
CronJob After Set -> 30 * * * *
ERROR! 401 {
  error: 'Only have permissions for subaccount LENDING',
  success: false
}
Only have permissions for subaccount LENDING
```

I create a subaccount LEDNING to provide lending and the API key is for subaccount LENDING (with trading permission) only:


```
root@#cat config.json
{
  "FTX_API_KEY": "API",
  "FTX_API_SECRET": "API",
  "CRON_JOB_AT_MINUTE": 30,
  "accounts": [
     {
      "subAccount": "LENDING",
      "lendingCoins": [
      { "coin": "USDT", "keepBalance": 0, "minimunHourlyRate": 0.000001 },
      { "coin": "XRP", "keepBalance": 0, "minimunHourlyRate": 0.000001 },
      { "coin": "BTC", "keepBalance": 0, "minimunHourlyRate": 0.000001 }
       ]
      }
    ]
}
```

The error looks it is unsuccessfully to me, however let's wait for a hour cycle to see if it is working.  8 )

**Comment by LuPoYi** [comment]
hmm...I'm not quite sure what's wrong with the permission, maybe you can try to create a new API key for All subaccount to fix that.

**Comment by meifiant** [comment]
I found what's the issue:
1. the subAcccount name is hardcode.  In my config.json I used different name, after I changed it to "LENDING", its working now.  You may give a reminder to user the subAccount name is hardcode.

And I put the command in background "root@# node main.js &", from my very limit linux command knowledge.  Is it the right way to keep it running?   In another word, if I kill the command "node main.js" it would be stop, right?

Thank you very much and appreciate your work and helpful.

**Comment by LuPoYi** [comment]
Thanks for your suggestion :)

For me, I use `tmux` to keep the process running. 

But sure, you can just use more simple command to execute this as background job
`nohup node main.js &`

More information here: https://stackoverflow.com/a/4797069/4401385

How to kill process:
`ps aux`  
find out which `pid` is and then
`kill -9 <pid>`

**Comment by meifiant** [comment]
Thank you very much for your guidance.  Wish you have a happy CNY and stay safe.
